version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trip-planner-api
    env_file:
      - .env
    environment:
      - OTEL_SERVICE_NAME=voyage-api
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-lgtm:4318
      - ENVIRONMENT=production
    networks:
      - default
      - internal-net

  web:
    image: nginx:alpine
    container_name: trip-planner-web
    ports:
      - "3001:80"
    volumes:
      - ./html-frontend:/usr/share/nginx/html:ro
    depends_on:
      api:
        condition: service_started
    networks:
      - default
      - internal-net

networks:
  default:
  internal-net:
    external: true
