import streamlit as st
import requests
import pandas as pd
import pydeck as pdk
from typing import Any
import json
import base64
from pathlib import Path
from frontend.functions import render_trip
from frontend.pdf_export import generate_trip_pdf
from frontend.styles import get_css

_img_path = Path(__file__).parent / "frontend" / "airplane.png"
with open(_img_path, "rb") as _f:
    _airplane_b64 = base64.b64encode(_f.read()).decode()

API_URL = "http://api:8000/plan-trip-stream"

st.set_page_config(
    page_title="Voyage",
    page_icon="frontend/airplane.png"
)

# ── Theme state ──────────────────────────────────────────────────────────────

if "theme" not in st.session_state:
    st.session_state.theme = "dark"

DARK = {
    "app_bg":          "#131313",
    "sidebar_bg":      "#1a1a19",
    "hero_grad_a":     "#262625",
    "hero_grad_b":     "#131313",
    "hero_border":     "#efd39533",
    "hero_title":      "#efd395",
    "hero_sub":        "#a4a4a4",
    "card_bg":         "#262625",
    "card_border":     "#4b4a48",
    "card_text":       "#a4a4a4",
    "card_title":      "#efd395",
    "section_text":    "#a4a4a4",
    "section_border":  "#efd395",
    "travel_time":     "#777674",
    "input_bg":        "#1e1e1d",
    "input_text":      "#a4a4a4",
    "chat_bg":         "#1e1e1d",
    "btn_bg":          "#262625",
    "btn_bg_hover":    "#333331",
    "btn_text":        "#a4a4a4",
    "btn_border":      "#4b4a48",
    "shadow":          "rgba(0,0,0,0.4)",
}

LIGHT = {
    "app_bg":          "#ffffff",
    "sidebar_bg":      "#fdf5f8",
    "hero_grad_a":     "#fdf0f5",
    "hero_grad_b":     "#ffffff",
    "hero_border":     "#f3e5ec99",
    "hero_title":      "#6b2d4a",
    "hero_sub":        "#555555",
    "card_bg":         "#fdf5f8",
    "card_border":     "#f3e5ec",
    "card_text":       "#333333",
    "card_title":      "#6b2d4a",
    "section_text":    "#2d2d2d",
    "section_border":  "#9e4d6a",
    "travel_time":     "#888888",
    "input_bg":        "#f7ecf1",
    "input_text":      "#333333",
    "chat_bg":         "#fdf5f8",
    "btn_bg":          "#ffffff",
    "btn_bg_hover":    "#fdf0f5",
    "btn_text":        "#333333",
    "btn_border":      "#d4a5b5",
    "shadow":          "rgba(0,0,0,0.08)",
}

T = DARK if st.session_state.theme == "dark" else LIGHT

# ── CSS ───────────────────────────────────────────────────────────────────────

st.markdown(get_css(T), unsafe_allow_html=True)

# ── Hero ──────────────────────────────────────────────────────────────────────

st.markdown(f"""
<div class="hero">
    <div class="hero-title">
        <img src="data:image/png;base64,{_airplane_b64}" style="height:44px;vertical-align:middle;margin-right:10px;">
        Voyage
    </div>
    <div class="hero-sub">
    Plan complete trips with hotels, restaurants, and itineraries generated by AI agents.
    </div>
</div>
""", unsafe_allow_html=True)

st.write("")

# ── Sidebar ───────────────────────────────────────────────────────────────────

st.sidebar.title("Voyage")

toggle_label = "☀️ Light mode" if st.session_state.theme == "dark" else "🌙 Dark mode"
if st.sidebar.button(toggle_label):
    st.session_state.theme = "light" if st.session_state.theme == "dark" else "dark"
    st.rerun()

st.sidebar.divider()
st.sidebar.subheader("History")

if "messages" not in st.session_state:
    st.session_state.messages = []

if "trips" not in st.session_state:
    st.session_state.trips = []

if "active_trip_idx" not in st.session_state:
    st.session_state.active_trip_idx = None

if st.sidebar.button("Restart"):
    st.session_state.messages = []
    st.session_state.trips = []
    st.session_state.active_trip_idx = None
    st.rerun()

st.sidebar.divider()

for i, trip in enumerate(st.session_state.trips):
    query_preview = trip["query"][:40] + "…" if len(trip["query"]) > 40 else trip["query"]
    label = f"**{trip['destination']}**\n{query_preview}"
    if st.sidebar.button(label, key=f"trip_{i}"):
        st.session_state.active_trip_idx = i
        st.rerun()

# ── Chat ──────────────────────────────────────────────────────────────────────

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

user_query = st.chat_input("Plan your trip...")

if user_query:

    st.session_state.active_trip_idx = None

    with st.chat_message("user"):
        st.markdown(user_query)

    st.session_state.messages.append({
        "role": "user",
        "content": user_query
    })

    with st.chat_message("assistant"):

        with st.spinner("Planning your trip..."):

            response = requests.post(
                API_URL,
                json={"query": user_query},
                stream=True
            )
            status_placeholder = st.empty()

            result = None

            for line in response.iter_lines():

                if line:

                    data = json.loads(line)
                    status = data["status"]

                    if status == "researching":
                        status_placeholder.write(" Researching destination...")

                    elif status == "research_done":
                        status_placeholder.write(f" Finding Attractions in {data['destination']}...")

                    elif status == "finding_hotels":
                        status_placeholder.write(" Finding hotels...")

                    elif status == "finding_food":
                        status_placeholder.write(" Discovering restaurants...")

                    elif status == "building_itinerary":
                        status_placeholder.write(" Building itinerary...")

                    elif status == "finalizing":
                        status_placeholder.write(" Reviewing travel plan...")

                    elif status == "done":
                        status_placeholder.write(" Trip plan ready!")
                        result = data["result"]

            if result:
                st.session_state.trips.append({
                    "query": user_query,
                    "destination": result["destination"],
                    "result": result
                })
                st.session_state.active_trip_idx = len(st.session_state.trips) - 1
                st.rerun()

# ── Render active trip (new or from history) ─────────────────────────────────

if st.session_state.active_trip_idx is not None:
    idx = st.session_state.active_trip_idx
    if idx < len(st.session_state.trips):
        active_trip = st.session_state.trips[idx]
        render_trip(active_trip["result"])
        pdf_file = generate_trip_pdf(active_trip["result"])
        st.download_button(
            label="Download Itinerary PDF",
            data=pdf_file,
            file_name=f"{active_trip['destination']}_trip_plan.pdf",
            mime="application/pdf",
            key="active_trip_pdf"
        )
