import streamlit as st
import requests
import pandas as pd
import pydeck as pdk
from typing import Any
import json
from frontend.functions import render_trip
from frontend.pdf_export import generate_trip_pdf

API_URL = "http://api:8000/plan-trip-stream"

st.set_page_config(
    page_title="AI Trip Planner",
    page_icon="🌍"
)

st.markdown("""
<style>

/* HERO CARD */

.hero {
    background: linear-gradient(
        90deg,
        var(--primaryColor),
        color-mix(in srgb, var(--primaryColor) 80%, var(--backgroundColor))
    );
    padding: 40px;
    border-radius: 12px;
    color: var(--primaryColor);
    text-align: center;
    box-shadow: 0 10px 30px color-mix(in srgb, var(--textColor) 20%, transparent);
}

/* HERO TEXT */

.hero-title {
    font-size: 42px;
    font-weight: 700;
    color: var(--primaryColor);
}

.hero-sub {
    font-size: 18px;
    opacity: 0.9;
    color: var(--textColor);
}

/* CARDS */

.card {
    background-color: var(--backgroundColorDarker);
    color: var(--textColor);
    padding: 20px;
    border-radius: 12px;
    box-shadow: 0 6px 20px color-mix(in srgb, var(--textColor) 20%, transparent);
    margin-bottom: 15px;
}

/* CARD TITLE */

.card-title {
    font-size: 18px;
    font-weight: 600;
    color: var(--textColor);
}

/* SECTION HEADER */

.section-header {
    font-size: 26px;
    font-weight: 700;
    margin-top: 25px;
    color: var(--textColor);
}

</style>
""", unsafe_allow_html=True)

st.markdown("""
<div class="hero">
    <div class="hero-title">🌍 AI Agent Trip Planner</div>
    <div class="hero-sub">
    Plan complete trips with hotels, restaurants, and itineraries generated by AI agents.
    </div>
</div>
""", unsafe_allow_html=True)

st.write("")

st.sidebar.title("History")



if "messages" not in st.session_state:
    st.session_state.messages = []

if "trips" not in st.session_state:
    st.session_state.trips = []

# Restart button
if st.button("Restart"):
    st.session_state.messages = []
    st.session_state.trips = []
    st.rerun()

for i, trip in enumerate(st.session_state.trips):

    if st.sidebar.button(trip["destination"], key=f"trip_{i}"):

        render_trip(trip["result"])

# Show chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# result container
result_container = st.container()
# User input
user_query = st.chat_input("Plan your trip...")

if user_query:

    result_container.empty()

    with st.chat_message("user"):
        st.markdown(user_query)

    st.session_state.messages.append({
        "role": "user",
        "content": user_query
    })

    with st.chat_message("assistant"):

        with st.spinner("Planning your trip..."):

            response = requests.post(
                API_URL,
                json={"query": user_query},
                stream=True
            )
            status_placeholder = st.empty()

            result = None

            for line in response.iter_lines():

                if line:

                    data = json.loads(line)

                    status = data["status"]

                    if status == "researching":
                        status_placeholder.write(" Researching destination...")
                    
                    elif status == "research_done":
                        status_placeholder.write(f" Finding Attractions in {data['destination']}...")  

                    elif status == "finding_hotels":
                        status_placeholder.write(" Finding hotels...")

                    elif status == "finding_food":
                        status_placeholder.write(" Discovering restaurants...")

                    elif status == "building_itinerary":
                        status_placeholder.write(" Building itinerary...")

                    elif status == "finalizing":
                        status_placeholder.write(" Reviewing travel plan...")

                    elif status == "done":
                        status_placeholder.write(" Trip plan ready!")
                        result = data["result"]

            #result = response.json()["result"]

            if result:
                st.session_state.trips.append({
                        "query": user_query,
                        "destination": result["destination"],
                        "result": result
                    })
                with result_container:
                    render_trip(result)
                pdf_file = generate_trip_pdf(result)

                st.download_button(
                    label="Download Trip Plan (PDF)",
                    data=pdf_file,
                    file_name=f"{result['destination']}_trip_plan.pdf",
                    mime="application/pdf"
                )

        # st.image(f"https://source.unsplash.com/1600x400/?{result['destination']},travel",
        #         use_container_width=True
        #         )
        # Destination




